<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-11 at 20:28:08.
 */
class SemExpert_ImportExportApi_Model_Import_Api_V2Test extends PHPUnit_Framework_TestCase {

    /**
     * @var SemExpert_ImportExportApi_Model_Import_Api_V2
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SemExpert_ImportExportApi_Model_Import_Api_V2;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

}
